// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotKayitSistemi.Models.DataContext;

#nullable disable

namespace NotKayitSistemi.Migrations
{
    [DbContext(typeof(NotKayitDbContext))]
    [Migration("20260223081004_asdgjk")]
    partial class asdgjk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.DersAlanKodTml", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DersAlanKodTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.DersTml", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DersAd")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("DersAlanKodId")
                        .HasColumnType("bigint");

                    b.Property<short>("KrediSayisi")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DersAlanKodId");

                    b.ToTable("DersTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.NotKodTml", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("NotKodTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.NotTml", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Deger")
                        .HasColumnType("float");

                    b.Property<long>("DersId")
                        .HasColumnType("bigint");

                    b.Property<long>("NotKodTmlId")
                        .HasColumnType("bigint");

                    b.Property<long>("OgrenciTmlId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("NotKodTmlId");

                    b.HasIndex("OgrenciTmlId");

                    b.ToTable("NotTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciAdres", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("OgrenciTmlId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciTmlId");

                    b.ToTable("OgrenciAdres");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciDers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DersId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("OgrenciTmlId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("OgrenciTmlId");

                    b.ToTable("OgrenciDers");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciIletisim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("OgrenciTmlId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Telefon")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OgrenciTmlId");

                    b.ToTable("OgrenciIletisim");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciTml", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("OgrenciTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.DersTml", b =>
                {
                    b.HasOne("NotKayitSistemi.Models.Entities.DersAlanKodTml", "DersAlanKodTml")
                        .WithMany("Dersler")
                        .HasForeignKey("DersAlanKodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DersAlanKodTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.NotTml", b =>
                {
                    b.HasOne("NotKayitSistemi.Models.Entities.DersTml", "DersTml")
                        .WithMany("Notlar")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotKayitSistemi.Models.Entities.NotKodTml", "NotKodTml")
                        .WithMany("Notlar")
                        .HasForeignKey("NotKodTmlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotKayitSistemi.Models.Entities.OgrenciTml", "OgrenciTml")
                        .WithMany("Notlar")
                        .HasForeignKey("OgrenciTmlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersTml");

                    b.Navigation("NotKodTml");

                    b.Navigation("OgrenciTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciAdres", b =>
                {
                    b.HasOne("NotKayitSistemi.Models.Entities.OgrenciTml", "OgrenciTml")
                        .WithMany("OgrenciAdresler")
                        .HasForeignKey("OgrenciTmlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgrenciTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciDers", b =>
                {
                    b.HasOne("NotKayitSistemi.Models.Entities.DersTml", "DersTml")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotKayitSistemi.Models.Entities.OgrenciTml", "OgrenciTml")
                        .WithMany("OgrenciDersler")
                        .HasForeignKey("OgrenciTmlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DersTml");

                    b.Navigation("OgrenciTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciIletisim", b =>
                {
                    b.HasOne("NotKayitSistemi.Models.Entities.OgrenciTml", "OgrenciTml")
                        .WithMany("OgrenciIletisim")
                        .HasForeignKey("OgrenciTmlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OgrenciTml");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.DersAlanKodTml", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.DersTml", b =>
                {
                    b.Navigation("Notlar");

                    b.Navigation("OgrenciDersler");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.NotKodTml", b =>
                {
                    b.Navigation("Notlar");
                });

            modelBuilder.Entity("NotKayitSistemi.Models.Entities.OgrenciTml", b =>
                {
                    b.Navigation("Notlar");

                    b.Navigation("OgrenciAdresler");

                    b.Navigation("OgrenciDersler");

                    b.Navigation("OgrenciIletisim");
                });
#pragma warning restore 612, 618
        }
    }
}
